# Generated by Django 4.1.3 on 2022-12-22 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(max_length=25)),
                ("nombre", models.CharField(max_length=25)),
                ("apellido", models.CharField(max_length=25)),
                ("telefono", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("fcomienzo", models.DateTimeField(auto_now_add=True)),
                ("ftermino", models.DateTimeField(null=True)),
                ("cobro", models.CharField(max_length=5)),
                ("ecobro", models.BooleanField(default=False)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
