# Generated by Django 4.1.3 on 2022-12-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pedidos", "0002_inventario_finanzas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedidos",
            old_name="ecobro",
            new_name="estado_del_cobro",
        ),
        migrations.RenameField(
            model_name="pedidos",
            old_name="fcomienzo",
            new_name="fecha_comienzo",
        ),
        migrations.RenameField(
            model_name="pedidos",
            old_name="ftermino",
            new_name="fecha_termino",
        ),
        migrations.AddField(
            model_name="finanzas",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
    ]
