# Generated by Django 4.1.3 on 2022-12-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pedidos", "0003_rename_ecobro_pedidos_estado_del_cobro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidos",
            name="fecha_termino",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
